# Generated by Django 5.1.3 on 2024-11-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='discoverer',
        ),
        migrations.DeleteModel(
            name='Discoverer',
        ),
    ]
