# Generated by Django 5.1.3 on 2024-11-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_remove_plant_discoverer_delete_discoverer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discoverer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='discoverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flora.discoverer'),
        ),
    ]
