# Generated by Django 5.1.3 on 2024-11-06 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_discoverer_plant_discoverer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='bloom_end',
            field=models.DateField(default=datetime.date(2000, 12, 31)),
        ),
        migrations.AddField(
            model_name='plant',
            name='bloom_start',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_season_end',
            field=models.DateField(default=datetime.date(2000, 9, 30)),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_season_start',
            field=models.DateField(default=datetime.date(2000, 4, 1)),
        ),
    ]
